### ISSUE TITLE
App Doesn't Start

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-pm#99]
Self-PM doesn't start due to an error parsing the cron job schedule:

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'payInvoices' defined in URL [jar:file:/home/pi/apps/self-pm/self-pm.jar!/BOOT-INF/classes!/com/selfxdsd/selfpm/PayInvoices.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Encountered invalid @Scheduled method 'payInvoices': Cron expression must consist of 6 fields (found 5 in "0 0 * * MON")
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]

```

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-06T07:14:07.719695``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske can you have a look when you have some time? :D  

Seems like Spring doesn't like that cron expression for ``payIncoices``

**Comment by criske** [comment]
@amihaiemil I'll fix this asap, it looks like spring doesn't like it (used it from here https://crontab.guru/every-monday).
I think `0 0 0 ? * MON` should work, but I will test it in a unit/integration test first.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
